/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualTourRouteImport } from './routes/virtual-tour'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as ExtracurricularRouteImport } from './routes/extracurricular'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BaloAiRouteImport } from './routes/balo-ai'
import { Route as AdminResetPasswordRouteImport } from './routes/admin-reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminAiRouteImport } from './routes/admin.ai'

const VirtualTourRoute = VirtualTourRouteImport.update({
  id: '/virtual-tour',
  path: '/virtual-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtracurricularRoute = ExtracurricularRouteImport.update({
  id: '/extracurricular',
  path: '/extracurricular',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BaloAiRoute = BaloAiRouteImport.update({
  id: '/balo-ai',
  path: '/balo-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin-reset-password',
  path: '/admin-reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/admin-reset-password': typeof AdminResetPasswordRoute
  '/balo-ai': typeof BaloAiRoute
  '/calendar': typeof CalendarRoute
  '/developers': typeof DevelopersRoute
  '/events': typeof EventsRoute
  '/extracurricular': typeof ExtracurricularRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/rules': typeof RulesRoute
  '/staff': typeof StaffRoute
  '/subjects': typeof SubjectsRoute
  '/virtual-tour': typeof VirtualTourRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-reset-password': typeof AdminResetPasswordRoute
  '/balo-ai': typeof BaloAiRoute
  '/calendar': typeof CalendarRoute
  '/developers': typeof DevelopersRoute
  '/events': typeof EventsRoute
  '/extracurricular': typeof ExtracurricularRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/rules': typeof RulesRoute
  '/staff': typeof StaffRoute
  '/subjects': typeof SubjectsRoute
  '/virtual-tour': typeof VirtualTourRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/api/chat': typeof ApiChatRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/admin-reset-password': typeof AdminResetPasswordRoute
  '/balo-ai': typeof BaloAiRoute
  '/calendar': typeof CalendarRoute
  '/developers': typeof DevelopersRoute
  '/events': typeof EventsRoute
  '/extracurricular': typeof ExtracurricularRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/rules': typeof RulesRoute
  '/staff': typeof StaffRoute
  '/subjects': typeof SubjectsRoute
  '/virtual-tour': typeof VirtualTourRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/admin-reset-password'
    | '/balo-ai'
    | '/calendar'
    | '/developers'
    | '/events'
    | '/extracurricular'
    | '/facilities'
    | '/gallery'
    | '/rules'
    | '/staff'
    | '/subjects'
    | '/virtual-tour'
    | '/admin/ai'
    | '/admin/knowledge'
    | '/api/chat'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/admin-reset-password'
    | '/balo-ai'
    | '/calendar'
    | '/developers'
    | '/events'
    | '/extracurricular'
    | '/facilities'
    | '/gallery'
    | '/rules'
    | '/staff'
    | '/subjects'
    | '/virtual-tour'
    | '/admin/ai'
    | '/admin/knowledge'
    | '/api/chat'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/admin-reset-password'
    | '/balo-ai'
    | '/calendar'
    | '/developers'
    | '/events'
    | '/extracurricular'
    | '/facilities'
    | '/gallery'
    | '/rules'
    | '/staff'
    | '/subjects'
    | '/virtual-tour'
    | '/admin/ai'
    | '/admin/knowledge'
    | '/api/chat'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  BaloAiRoute: typeof BaloAiRoute
  CalendarRoute: typeof CalendarRoute
  DevelopersRoute: typeof DevelopersRoute
  EventsRoute: typeof EventsRoute
  ExtracurricularRoute: typeof ExtracurricularRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  RulesRoute: typeof RulesRoute
  StaffRoute: typeof StaffRoute
  SubjectsRoute: typeof SubjectsRoute
  VirtualTourRoute: typeof VirtualTourRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-tour': {
      id: '/virtual-tour'
      path: '/virtual-tour'
      fullPath: '/virtual-tour'
      preLoaderRoute: typeof VirtualTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extracurricular': {
      id: '/extracurricular'
      path: '/extracurricular'
      fullPath: '/extracurricular'
      preLoaderRoute: typeof ExtracurricularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balo-ai': {
      id: '/balo-ai'
      path: '/balo-ai'
      fullPath: '/balo-ai'
      preLoaderRoute: typeof BaloAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reset-password': {
      id: '/admin-reset-password'
      path: '/admin-reset-password'
      fullPath: '/admin-reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  BaloAiRoute: BaloAiRoute,
  CalendarRoute: CalendarRoute,
  DevelopersRoute: DevelopersRoute,
  EventsRoute: EventsRoute,
  ExtracurricularRoute: ExtracurricularRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  RulesRoute: RulesRoute,
  StaffRoute: StaffRoute,
  SubjectsRoute: SubjectsRoute,
  VirtualTourRoute: VirtualTourRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
